Disable unnecessary integrity checks during deserialization
Mutagen-Modding/Spriggit pull request #27
Opened 2023-09-11 10:03 UTC by metacubed

This commit removes various checks which could unintentionally change mod contents or metadata as it gets deserialized into a plugin. Without this fix, round-tripping could cause differences in the generated files without any intentional user changes.

Some of these unintentional changes are:
- Cleaning or reordering the list of masters
- Changing mod record stats such as record count and next record

Fixes #25.

2023-09-11 18:37 UTC, Noggog requested changes

2023-09-11 18:37 UTC, Noggog commented on Spriggit.Core/Spriggit.Core.csproj
> +        <PackageReference Include="Mutagen.Bethesda.Core" />
I think `Spriggit.Core` is trying to have minimal imports, so as to reduce collision issues when loading translation packages in.   If I recall, this will cause problems in other subtle areas when loading two translation packages that differ too much (maybe I'll add a comment to this effect)

I think either:
- We'll need to copy paste the NoCheckWriteParameters to each end package (blech)
- We'll need to define another library that is shared among entry points, but not imported by the engine.  So maybe `Spriggit.Core.EntryPoints` or somesuch.   This should avoid the reflection collisions while having a common area for Entry Point logic

2023-09-11 19:17 UTC, metacubed commented on Spriggit.Core/Spriggit.Core.csproj
> +        <PackageReference Include="Mutagen.Bethesda.Core" />
Exactly, I was wondering what the right place would be, for that constant. A new library sounds all right to me. 👍

2023-09-11 19:21 UTC, metacubed commented on Spriggit.Core/Spriggit.Core.csproj
> +        <PackageReference Include="Mutagen.Bethesda.Core" />
Also, we could further reduce the common code in all the entry points by moving it into a common base class (separate PR, of course).

I did see a code comment about auto-generation in one of the EntryPoint classes, so wanted to check what your plans were.

2023-09-11 19:26 UTC, Noggog commented on Spriggit.Core/Spriggit.Core.csproj
> +        <PackageReference Include="Mutagen.Bethesda.Core" />
Not sure how much common code exists between EntryPoints, but feel free to take a stab at reducing what you can.

That TryGetMetaInfo has a little bit of code that potentially could be autogenerated, but that work would be on the `Mutagen.Bethesda.Serialization` side of generating the TryGetMetaInfo call, which the entry points would mostly forward along.   It's not too much copy pasted code, which is why it's a bit low priority

2023-10-02 00:01 UTC, Noggog commented
Heya!  Just seeing if you want to finish up the loose ends on this.  Otherwise I can finish it off myself as well

2023-10-03 22:17 UTC, merged